name: ZIP release assets
on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip assets
      run: cd .. && mkdir -p MMMGdkp && cp -R GDKPd-Classic/* MMMGdkp && rm -rf MMMGdkp/.git && zip -r MMMGdkp.zip MMMGdkp && mv MMMGdkp.zip GDKPd-Classic/
    - name: Release to Github
      run: echo "Release"
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MMMGdkp.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
